### ISSUE TITLE
Data errors

### ISSUE THREAD

**Issue by Huh** [Lukacs-Lab/Columbia-Spotted-Frogs#35]
I do not think that the primary periods are correct in the data.  

For example, the following code

```
table(as.numeric(fEH$prim))
```

produces

```
   1     2     4     6     8     9    10    11    12    13    14    15    16    17 
19596 16330 13064 13064 13064 13064 13064 13064 13064 13064 13064 13064 13064 13064 
```

I noticed this when trying to look at the primary period in which animals were captured using

```
first <- tapply(prim, ind, min)
```

Every individual was apparently caught during the first primary period, is this correct?  It does not seem so.

**Comment by Huh** [comment]
I would suggest Charlie and Sara take a look at this, but I am assigning Charlie to keep things rolling.

**Comment by Huh** [comment]
Also note that there are 17 primary periods, but there should only be 14 per my conversation with Rebecca yesterday.  Please correct me if I am wrong.

**Comment by Huh** [comment]
I think I fixed it...

```
        #  Find first and last primary period for each individual
        first <- tapply(prim[fEH$cap == 1], ind[fEH$cap == 1], min)
        last <- tapply(prim[fEH$cap == 1], ind[fEH$cap == 1], max)
```

**Comment by williash23** [comment]
Hey Josh - I've been working through your changes...trying to understand
what's going on. (figured I should at least give it a shot before I ask for
help :) ).

Primary periods....as I understand it there are 14 different primary
periods but the original numbering of them goes from 1 to 17 because
periods 3, 5 and 7 were not sampled. I.e. we have original labels 1, 2, 4,
6, 8, 9, 10, 11, 12, 13, 14, 15, 16 and 17.
